- name: deployment_name
  value: boinc-1
  default: boinc-1
  description: "Name of the deployment job"

- name: cpu_workers
  value: "1"
  default: "2"
  description: "Maximum number of workers to spawn in the cluster"

- name: gpu_workers
  value: "1"
  default: "2"
  description: "Maximum number of workers to spawn in the cluster"

- name: email
  value: "carlos@kalavai.net"
  default: "carlos@kalavai.net"
  description: "Maximum number of workers to spawn in the cluster"

- name: password
  value: "kalavaipool"
  default: "kalavaipool"
  description: "Maximum number of workers to spawn in the cluster"

- name: min_cpus
  value: "4"
  default: "4"
  description: "CPUs per single worker (final one = cpus * num_workers)"

- name: max_cpus
  value: "16"
  default: "16"
  description: "CPUs per single worker (final one = cpus * num_workers)"

- name: min_memory
  value: "4"
  default: "4"
  description: "RAM memory per single worker (final one = memory * num_workers)"

- name: max_memory
  value: "16"
  default: "16"
  description: "RAM memory per single worker (final one = memory * num_workers)"

- name: gpus
  value: "1"
  default: "1"
  description: "GPUs per single worker (final one = gpus * num_workers)"

# - name: endpoint_ports
#   value: "8080"
#   default: "8080"
#   description: "[DO NOT CHANGE] Ports opened on master node (will be shown as endpoints for the job)"