site_name: Kalavai Documentation
nav:
  - Getting started:
    - Welcome to Kalavai: index.md
    - Concepts: concepts.md
    - Getting started: getting_started.md
    - Choosing job resources: choose_job_resources.md
    - Compatibility: compatibility.md
    - CLI: cli.md
  - Examples cases:
    - Self-hosted LLM pool: self_hosted_llm_pool.md
  - Applications: 
    - Job templates: templates.md
  - Managed platform:
    - Overview: managed/overview.md
    - Ray Cluster: managed/ray.md
    - GPUStack: managed/gpustack.md
  - Use cases:
    - Fine tune with Axolotl: managed/fine_tuning.md
    - Multi-GPU model hosting: managed/cogenai.md
    #- Autoscaling LLMs with requests
    #- Distributed on-demand python: kubetorch

theme:
  name: shadcn
  show_title: true
  navigation_depth: 3
  #icon: assets/icons/logo_no_background.png
  show_stargazers: false
  pygments_style: # default styles 
    light: shadcn-light
    dark: github-dark
  topbar_sections: false
  show_datetime: false
  favicon: assets/icons/browser.png
  features:
    - navigation.sections
    - navigation.instant
    - navigation.instant.progress
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
  palette:
  # Palette toggle for dark mode
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

markdown_extensions:
  - attr_list
  - fenced_code # https://asiffer.github.io/mkdocs-shadcn/extensions/fenced_code/
  - codehilite # code highlight https://asiffer.github.io/mkdocs-shadcn/extensions/codehilite/
  - shadcn.extensions.codexec
  - admonition # warning/info messages https://asiffer.github.io/mkdocs-shadcn/extensions/admonition/
  - pymdownx.blocks.caption # figure captions https://asiffer.github.io/mkdocs-shadcn/extensions/pymdownx_blocks_caption/
  - pymdownx.blocks.details # collapsable block https://asiffer.github.io/mkdocs-shadcn/extensions/pymdownx_blocks_details/
  - pymdownx.blocks.tab # tabs https://asiffer.github.io/mkdocs-shadcn/extensions/pymdownx_blocks_tab/

plugins:
  - search
  - excalidraw
  - mkdocstrings
  