site_name: Kalavai Documentation
nav:
  - Getting started:
    - Welcome to Kalavai: index.md
    - Concepts: concepts.md
    - Getting started: getting_started.md
    - Compatibility: compatibility.md
  - Interface:
    - Connect to remote pool: remote_pool.md
    - CLI: cli.md
    - Browser GUI: gui.md 
  - Use cases:
    - Multi-GPU LLM: use_cases/multi_gpu_inference.md
    - Fine tune: use_cases/fine_tuning.md
    #- Autoscaling deployments:
    - BYO Model Gateway: use_cases/self_hosted_llm_pool.md
    - Easy LLMs with GPUstack: use_cases/gpustack.md 
    - Production GPU fleets: use_cases/ray.md
  - Managed platform:
    - Overview: managed/overview.md

theme:
  name: shadcn
  show_title: true
  navigation_depth: 3
  #icon: assets/icons/logo_no_background.png
  show_stargazers: false
  pygments_style: # default styles 
    light: shadcn-light
    dark: github-dark
  topbar_sections: false
  show_datetime: false
  favicon: assets/icons/browser.png
  features:
    - navigation.sections
    - navigation.instant
    - navigation.instant.progress
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
  palette:
  # Palette toggle for dark mode
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

markdown_extensions:
  - attr_list
  - fenced_code # https://asiffer.github.io/mkdocs-shadcn/extensions/fenced_code/
  - codehilite # code highlight https://asiffer.github.io/mkdocs-shadcn/extensions/codehilite/
  - shadcn.extensions.codexec
  - admonition # warning/info messages https://asiffer.github.io/mkdocs-shadcn/extensions/admonition/
  - pymdownx.blocks.caption # figure captions https://asiffer.github.io/mkdocs-shadcn/extensions/pymdownx_blocks_caption/
  - pymdownx.blocks.details # collapsable block https://asiffer.github.io/mkdocs-shadcn/extensions/pymdownx_blocks_details/
  - pymdownx.blocks.tab # tabs https://asiffer.github.io/mkdocs-shadcn/extensions/pymdownx_blocks_tab/

plugins:
  - search
  - excalidraw
  - mkdocstrings
  