site_name: Kalavai Documentation
site_url: https://kalavai-net.github.io/kalavai-client
use_directory_urls: true
nav:
  - Geting started:
    - Quick intro:
      - Overview: index.md
      - Quick Start: getting_started.md
      - Compatibility: compatibility.md
    - Configure nodes:
      - NVIDIA: nvidia_node.md
      - AMD: amd_node.md
      - Windows: windows_node.md
    - Interface:
      - CLI: cli.md
      - Browser GUI: gui.md
      - Connect to remote pool: remote_pool.md 
  - Use cases:
    - GPU clusters:
      - Easy LLMs with GPUstack: use_cases/gpustack.md 
      - Production GPU fleets: use_cases/ray.md
    - Tuning:
      - Fine tune: use_cases/fine_tuning.md
    - Inference:
      - Multi-GPU LLM: use_cases/multi_gpu_inference.md
      - BYO Model Gateway: use_cases/self_hosted_llm_pool.md
  - Managed platform:
    - Overview: managed/overview.md

theme:
  name: shadcn
  show_title: true
  navigation_depth: 3
  #icon: assets/icons/logo_no_background.png
  show_stargazers: false
  pygments_style: # default styles 
    light: shadcn-light
    dark: github-dark
  topbar_sections: true
  show_datetime: false
  favicon: assets/icons/browser.png
  features:
    - navigation.sections
    - navigation.instant
    - navigation.instant.progress
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
  palette:
  # Palette toggle for dark mode
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

markdown_extensions:
  - attr_list
  - fenced_code # https://asiffer.github.io/mkdocs-shadcn/extensions/fenced_code/
  - codehilite # code highlight https://asiffer.github.io/mkdocs-shadcn/extensions/codehilite/
  - shadcn.extensions.codexec
  - admonition # warning/info messages https://asiffer.github.io/mkdocs-shadcn/extensions/admonition/
  - pymdownx.blocks.caption # figure captions https://asiffer.github.io/mkdocs-shadcn/extensions/pymdownx_blocks_caption/
  - pymdownx.blocks.details # collapsable block https://asiffer.github.io/mkdocs-shadcn/extensions/pymdownx_blocks_details/
  - pymdownx.blocks.tab # tabs https://asiffer.github.io/mkdocs-shadcn/extensions/pymdownx_blocks_tab/

plugins:
  - search
  - excalidraw
  - mkdocstrings
  